
package com.cw.stu.internet.tech.cxf.client.wsdl.wsimport.hello;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWS", targetNamespace = "http://www.tmp.com/services/hello")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWS {


    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "welcome", targetNamespace = "http://www.tmp.com/services/hello", className = "Welcome")
    @ResponseWrapper(localName = "welcomeResponse", targetNamespace = "http://www.tmp.com/services/hello", className = "WelcomeResponse")
    public String welcome(
            @WebParam(name = "name", targetNamespace = "")
                    String name);

}
